import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FileText, Download, Eye, Calendar, User, Activity, Search, Filter, X, Printer } from 'lucide-react'

const mockReports = [
  { id: 1, patient: 'Sarah Johnson', date: '2024-03-15', risk: 'Low Risk', type: 'Assessment', bp: '118/78', sugar: '95', confidence: '92%', age: 28, weeks: 24, temp: 98.4, heart_rate: 72, notes: 'All vitals normal. Continue routine prenatal care.' },
  { id: 2, patient: 'Emily Davis', date: '2024-03-14', risk: 'Medium Risk', type: 'Assessment', bp: '138/88', sugar: '142', confidence: '78%', age: 32, weeks: 28, temp: 98.8, heart_rate: 82, notes: 'Elevated blood pressure and sugar. Recommend increased monitoring.' },
  { id: 3, patient: 'Maria Garcia', date: '2024-03-14', risk: 'High Risk', type: 'Alert', bp: '158/98', sugar: '165', confidence: '89%', age: 35, weeks: 32, temp: 100.2, heart_rate: 95, notes: 'High risk detected. Immediate medical attention required.' },
  { id: 4, patient: 'Lisa Chen', date: '2024-03-13', risk: 'Low Risk', type: 'Assessment', bp: '115/75', sugar: '92', confidence: '95%', age: 26, weeks: 20, temp: 98.2, heart_rate: 68, notes: 'Healthy pregnancy progress. Maintain current lifestyle.' },
  { id: 5, patient: 'Anna Smith', date: '2024-03-12', risk: 'Medium Risk', type: 'Follow-up', bp: '135/85', sugar: '128', confidence: '71%', age: 30, weeks: 26, temp: 98.6, heart_rate: 78, notes: 'Slightly elevated values. Follow-up in 2 weeks.' },
]

export default function Reports() {
  const [searchTerm, setSearchTerm] = useState('')
  const [filterRisk, setFilterRisk] = useState('all')
  const [selectedReport, setSelectedReport] = useState(null)

  const filteredReports = mockReports.filter(report => {
    const matchesSearch = report.patient.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesFilter = filterRisk === 'all' || report.risk.toLowerCase().includes(filterRisk.toLowerCase())
    return matchesSearch && matchesFilter
  })

  const handleView = (report) => {
    setSelectedReport(report)
  }

  const handleDownload = (report) => {
    const content = `
MATERNAL RISK ASSESSMENT REPORT
================================
Patient: ${report.patient}
Date: ${report.date}
Risk Level: ${report.risk}
Type: ${report.type}

VITAL SIGNS
-----------
Age: ${report.age} years
Pregnancy Weeks: ${report.weeks}
Blood Pressure: ${report.bp} mmHg
Blood Sugar: ${report.sugar} mg/dL
Body Temperature: ${report.temp}°F
Heart Rate: ${report.heart_rate} bpm

ASSESSMENT
----------
Confidence: ${report.confidence}
Notes: ${report.notes}

================================
Generated by AI Maternal Risk Prediction System
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `report_${report.patient.replace(/\s+/g, '_')}_${report.date}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const closeModal = () => {
    setSelectedReport(null)
  }

  return (
    <div className="space-y-8">
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <h1 className="text-4xl font-bold mb-2">
          <span className="gradient-text">Reports</span>
        </h1>
        <p className="text-gray-400">View and manage patient assessment reports</p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="glass-card rounded-2xl p-6"
      >
        <div className="flex flex-col md:flex-row gap-4 mb-6">
          <div className="flex-1 relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search patients..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full glass-input rounded-xl pl-12 pr-4 py-3 outline-none"
            />
          </div>
          <div className="flex gap-2">
            {['all', 'low', 'medium', 'high'].map((filter) => (
              <button
                key={filter}
                onClick={() => setFilterRisk(filter)}
                className={`px-4 py-2 rounded-xl font-medium transition-all ${
                  filterRisk === filter
                    ? 'bg-gradient-to-r from-cyan-500 to-purple-500 text-white'
                    : 'glass hover:bg-white/10'
                }`}
              >
                {filter === 'all' ? 'All' : `${filter} Risk`}
              </button>
            ))}
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-white/10">
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Patient</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Date</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Type</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Risk Level</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Vitals</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Confidence</th>
                <th className="text-left py-3 px-4 text-gray-400 font-medium">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredReports.map((report, index) => (
                <motion.tr
                  key={report.id}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="border-b border-white/5 hover:bg-white/5 transition-colors"
                >
                  <td className="py-3 px-4">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-purple-500 flex items-center justify-center">
                        <User className="w-5 h-5" />
                      </div>
                      <span className="font-medium">{report.patient}</span>
                    </div>
                  </td>
                  <td className="py-3 px-4 text-gray-400">
                    <div className="flex items-center gap-2">
                      <Calendar className="w-4 h-4" />
                      {report.date}
                    </div>
                  </td>
                  <td className="py-3 px-4">
                    <span className="px-3 py-1 rounded-full text-xs bg-white/10">
                      {report.type}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                      report.risk === 'Low Risk' ? 'bg-green-500/20 text-green-400' :
                      report.risk === 'Medium Risk' ? 'bg-yellow-500/20 text-yellow-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {report.risk}
                    </span>
                  </td>
                  <td className="py-3 px-4">
                    <div className="text-sm">
                      <div className="flex items-center gap-1">
                        <Activity className="w-3 h-3 text-red-400" />
                        {report.bp}
                      </div>
                      <div className="text-gray-400">Sugar: {report.sugar}</div>
                    </div>
                  </td>
                  <td className="py-3 px-4">{report.confidence}</td>
                  <td className="py-3 px-4">
                    <div className="flex gap-2">
                      <motion.button
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => handleView(report)}
                        className="p-2 rounded-lg bg-white/10 hover:bg-white/20"
                        title="View Report"
                      >
                        <Eye className="w-4 h-4" />
                      </motion.button>
                      <motion.button
                        whileHover={{ scale: 1.1 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={() => handleDownload(report)}
                        className="p-2 rounded-lg bg-white/10 hover:bg-white/20"
                        title="Download Report"
                      >
                        <Download className="w-4 h-4" />
                      </motion.button>
                    </div>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      </motion.div>

      <AnimatePresence>
        {selectedReport && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4"
            onClick={closeModal}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="glass-card rounded-2xl p-6 max-w-2xl w-full max-h-[90vh] overflow-y-auto"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-2xl font-bold flex items-center gap-2">
                  <FileText className="w-6 h-6 text-maternal-pink" />
                  Report Details
                </h2>
                <button
                  onClick={closeModal}
                  className="p-2 rounded-lg bg-white/10 hover:bg-white/20"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Patient Name</p>
                    <p className="font-semibold text-lg">{selectedReport.patient}</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Date</p>
                    <p className="font-semibold text-lg">{selectedReport.date}</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Age</p>
                    <p className="font-semibold text-lg">{selectedReport.age} years</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Pregnancy Weeks</p>
                    <p className="font-semibold text-lg">{selectedReport.weeks} weeks</p>
                  </div>
                </div>

                <div className="p-4 rounded-xl bg-white/5">
                  <p className="text-gray-400 text-sm mb-2">Risk Level</p>
                  <span className={`px-4 py-2 rounded-full text-lg font-medium ${
                    selectedReport.risk === 'Low Risk' ? 'bg-green-500/20 text-green-400' :
                    selectedReport.risk === 'Medium Risk' ? 'bg-yellow-500/20 text-yellow-400' :
                    'bg-red-500/20 text-red-400'
                  }`}>
                    {selectedReport.risk}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Blood Pressure</p>
                    <p className="font-semibold text-xl">{selectedReport.bp} mmHg</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Blood Sugar</p>
                    <p className="font-semibold text-xl">{selectedReport.sugar} mg/dL</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Body Temperature</p>
                    <p className="font-semibold text-xl">{selectedReport.temp}°F</p>
                  </div>
                  <div className="p-4 rounded-xl bg-white/5">
                    <p className="text-gray-400 text-sm">Heart Rate</p>
                    <p className="font-semibold text-xl">{selectedReport.heart_rate} bpm</p>
                  </div>
                </div>

                <div className="p-4 rounded-xl bg-white/5">
                  <p className="text-gray-400 text-sm mb-2">Assessment Notes</p>
                  <p className="text-lg">{selectedReport.notes}</p>
                </div>

                <div className="flex gap-3 pt-4">
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => handleDownload(selectedReport)}
                    className="flex-1 py-3 bg-maternal-purple hover:bg-maternal-violet rounded-xl font-semibold flex items-center justify-center gap-2"
                  >
                    <Download className="w-5 h-5" />
                    Download Report
                  </motion.button>
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => window.print()}
                    className="py-3 px-6 glass hover:bg-white/10 rounded-xl font-semibold flex items-center justify-center gap-2"
                  >
                    <Printer className="w-5 h-5" />
                    Print
                  </motion.button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
